from .FCN8s import *
from .FCN16s import *
from .FCN32s import *
from .FCN_ResNet50 import *
from .FCN_ResNet101 import *
from .FPN import *
from .Unet import *
from .UPPnet import *
from .DeepLabV3Plus import *
from .DeepLabV3Plus_ResNet50 import *
from .DeepLabV3Plus_ResNet101 import *
from .AlignedXception import *