from .FCN8s import *
from .FCN16s import *
from .FCN32s import *
from .FCN_ResNet50 import *
from .FCN_ResNet101 import *
from .Unet_Efficient_b0 import *
from .Unet_Efficient_b5 import *
from .UPlusPlus_Efficient_b4 import *
from .DeepLabV3Plus_Efficient_b4 import *
from .DeepLabV3Plus_Efficient_b7 import *
from .DeepLabV3Plus_Xception import *
from .DeepLabV3Plus_ResNet50 import *
from .DeepLabV3Plus_ResNet101 import *
from .UPlusPlus_ResNet101 import *
from .UPlusPlus_Efficient_b5 import *
